version: '3'

volumes:
  data:

services:
  db:
    image: mysql
    volumes:
      - data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: fimly_user
      MYSQL_PASSWORD: fimly_secret
      MYSQL_DATABASE: fimly_db
      MYSQL_ROOT_PASSWORD: secret

  app:
    image: bdfin/fimly
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment: 
      - DB_HOST=db
      - ASPNETCORE_ENVIRONMENT=Production