version: '3'

volumes:
  fimly_data:

services:
  fimly_mysql:
    image: mysql
    volumes:
      - fimly_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: fimly_user
      MYSQL_PASSWORD: fimly_secret
      MYSQL_DATABASE: fimly_db
      MYSQL_ROOT_PASSWORD: secret

  fimly_app:
    image: bdfin/fimly
    depends_on:
      - fimly_mysql
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment: 
      - DB_HOST=fimly_mysql